apiVersion: apps/v1
kind: Deployment
metadata:
  name: human-proxy-api
spec:
  replicas: {{ .Values.api.replicaCount }}
  selector:
    matchLabels:
      app: human-proxy-api
  template:
    metadata:
      labels:
        app: human-proxy-api
    spec:
      containers:
        - name: api
          image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}"
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /internal/health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /internal/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          ports:
            - containerPort: 8080
