{{- if .Values.web.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: human-proxy-web
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: human-proxy-web
  minReplicas: {{ .Values.web.hpa.minReplicas }}
  maxReplicas: {{ .Values.web.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.web.hpa.targetCpuUtilizationPercentage }}
{{- end }}
