apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: human-proxy-root
spec:
  project: default
  source:
    repoURL: https://github.com/CaChiJ/human-proxy.git
    targetRevision: main
    path: infra/k8s/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
