web:
  image:
    tag: latest
  replicaCount: 3
  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 10

api:
  image:
    tag: latest
  replicaCount: 3
  hpa:
    enabled: true
    minReplicas: 3
    maxReplicas: 12
